dist: xenial   # required for Python >= 3.7

sudo: false

language: python

cache: pip

python:
#  - "3.5"
  - "3.6"
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  - "pypy3.5"  # Pypy3 3.5.3

install:
  - make deps

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)